#ifndef __SCR_CLOCK_SETTING_H__
#define __SCR_CLOCK_SETTING_H__

#include "screens.h"

#define SCR_CLOCK_SETTING_ITEM_NUMBER (8)
#define SCR_CLOCK_SETTING_FRAME_X (2)
#define SCR_CLOCK_SETTING_FRAME_Y_1 (2)
#define SCR_CLOCK_SETTING_FRAME_STEP (12)
#define SCR_CLOCK_SETTING_FRAME_W (124)
#define SCR_CLOCK_SETTING_FRAME_H (11)
#define SCR_CLOCK_SETTING_FRAME_R (2)

typedef enum
{
	SCR_CLOCK_SETTING_TIME,
	SCR_CLOCK_SETTING_DISPLAY,
	SCR_CLOCK_SETTING_COLOR,
	SCR_CLOCK_SETTING_BRIGHT,
	SCR_CLOCK_SETTING_SOUND,
	SCR_CLOCK_SETTING_CHIME,
	SCR_CLOCK_SETTING_RESET,
	SCR_CLOCK_SETTING_EXIT,
} scr_clock_setting_item_t;

#endif //__SCR_CLOCK_SETTING_H__
