#ifndef __SCR_CLOCK_SETTING_SOUND_H__
#define __SCR_CLOCK_SETTING_SOUND_H__

#include "screens.h"

#define SCR_CLOCK_SETTING_SOUND_ITEM_NUMBER (3)

typedef enum
{
	SCR_CLOCK_SETTING_SOUND_MUTE,
	SCR_CLOCK_SETTING_SOUND_CHIME,
	SCR_CLOCK_SETTING_SOUND_BACK,
} scr_clock_setting_sound_item_t;

#endif //__SCR_CLOCK_SETTING_SOUND_H__
