#ifndef __SCR_CLOCK_SETTING_H__
#define __SCR_CLOCK_SETTING_H__

#include "screens.h"

#define SCR_CLOCK_SETTING_ITEM_NUMBER (5)
#define SCR_CLOCK_SETTING_FRAME_X (2)
#define SCR_CLOCK_SETTING_FRAME_Y_1 (4)
#define SCR_CLOCK_SETTING_FRAME_STEP (14)
#define SCR_CLOCK_SETTING_FRAME_W (124)
#define SCR_CLOCK_SETTING_FRAME_H (12)
#define SCR_CLOCK_SETTING_FRAME_R (2)

typedef enum
{
	SCR_CLOCK_SETTING_TIME,
	SCR_CLOCK_SETTING_COLOR,
	SCR_CLOCK_SETTING_LAYOUT,
	SCR_CLOCK_SETTING_SOUND,
	SCR_CLOCK_SETTING_EXIT,
} scr_clock_setting_item_t;

#endif //__SCR_CLOCK_SETTING_H__
