#ifndef __SCR_CLOCK_MENU_H__
#define __SCR_CLOCK_MENU_H__

#include "screens.h"

#define SCR_CLOCK_MENU_ITEM_NUMBER (6)
#define SCR_CLOCK_MENU_ICON_X (52)
#define SCR_CLOCK_MENU_ICON_Y (18)

typedef enum
{
	SCR_CLOCK_MENU_CLOCK,
	SCR_CLOCK_MENU_ALARM,
	SCR_CLOCK_MENU_STOPWATCH,
	SCR_CLOCK_MENU_TIMER,
	SCR_CLOCK_MENU_SETTING,
	SCR_CLOCK_MENU_EXIT,
} scr_clock_menu_item_t;

#endif //__SCR_CLOCK_MENU_H__
