#ifndef __SCR_CLOCK_TIME_SETTING_H__
#define __SCR_CLOCK_TIME_SETTING_H__

#include "screens.h"
#include "mc_clock_clock.h"

#define SCR_CLOCK_TIME_SETTING_YEAR_MIN (2000)
#define SCR_CLOCK_TIME_SETTING_YEAR_MAX (2099)

typedef enum
{
	SCR_CLOCK_TIME_SETTING_YEAR,
	SCR_CLOCK_TIME_SETTING_MONTH,
	SCR_CLOCK_TIME_SETTING_DATE,
	SCR_CLOCK_TIME_SETTING_WEEKDAY,
	SCR_CLOCK_TIME_SETTING_HOUR,
	SCR_CLOCK_TIME_SETTING_MIN,
	SCR_CLOCK_TIME_SETTING_SEC,
	SCR_CLOCK_TIME_SETTING_SAVE,
	SCR_CLOCK_TIME_SETTING_FIELD_NUMBER,
} scr_clock_time_setting_field_t;

#endif //__SCR_CLOCK_TIME_SETTING_H__
